### ISSUE TITLE
Console.ReadKey()

### ISSUE THREAD

**Issue by haukot** [ulmic/MIC_Enterprise#4]
Писать код навроде

``` c#
 try {
                con = new MySqlConnection(connectionString);
            } catch {
                Console.WriteLine("Error: couldn't connect to database");
                Console.ReadKey();
                return null;
            } 
```

хуевая идея, ибо _Console.WriteLine_ сработает во внутреннюю консоль студии, а вот на _Console.ReadKey_ упадет, ибо внутренняя консоль студии не ждет нажатий.

**Comment by kalashnikovisme** [comment]
Во-первых, не матерись! Во-вторых, это Олега код :)

**Comment by haukot** [comment]
окай. Про мат - я думал, issues приватные)

**Comment by haukot** [comment]
И кста, Олега код или нет - такой код выдает эксепшен. В cathc'e) оцени юмор ситуации

**Comment by kalashnikovisme** [comment]
Я видел много раз, когда не включал сервер :)

**Comment by kalashnikovisme** [comment]
Убрал все консоль строки.
