### ISSUE TITLE
GodFather

### ISSUE THREAD

**Issue by haukot** [ulmic/MIC_Enterprise#5]
Крестные определяются криво(неверно). Хз, косяк в базе или проге, но он есть.

**Comment by kalashnikovisme** [comment]
В данный момент переношу приложение на новую базу. Как только переложу, будет понятно, где косяк.

**Comment by kalashnikovisme** [comment]
Проверь сейчас крёстных.

**Comment by kalashnikovisme** [comment]
А ты, сука, @haukot нихуя не проверил...
